headers = []
redirects = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Projects\\Misrad-AI\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run security:scan-api-guards && NODE_OPTIONS='--max-old-space-size=6144' npm run build"

[build.environment]
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"
NODE_OPTIONS = "--max-old-space-size=6144"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]